# Generated by Django 4.2.23 on 2025-06-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Metier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pays",
                        to="famille.continent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villes",
                        to="famille.pays",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "code_unique",
                    models.CharField(
                        blank=True, max_length=150, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
                ("prenom", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("date_decce", models.DateField(blank=True, null=True)),
                (
                    "mari",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="father_from_mother",
                        to="famille.person",
                    ),
                ),
                (
                    "mere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_from_mother",
                        to="famille.person",
                    ),
                ),
                (
                    "metier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personne",
                        to="famille.metier",
                    ),
                ),
                (
                    "pere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_from_father",
                        to="famille.person",
                    ),
                ),
                (
                    "reseidence_actuel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residence",
                        to="famille.ville",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Famille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familles",
                        to="famille.district",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="district",
            name="ville",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="famille.ville",
            ),
        ),
        migrations.CreateModel(
            name="Cotisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateField(auto_now_add=True)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("OM", "Orange Money"),
                            ("CB", "Carte Bancaire"),
                            ("CH", "Chèque"),
                            ("ES", "Espèces"),
                        ],
                        max_length=2,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("motif", models.CharField(blank=True, max_length=255)),
                (
                    "personne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotisations",
                        to="famille.person",
                    ),
                ),
            ],
        ),
    ]
