# Generated by Django 4.2.23 on 2025-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="est_vivant",
            field=models.CharField(
                choices=[("V", "VIVANT"), ("D", "Décedé")], max_length=1
            ),
        ),
    ]
