# Generated by Django 5.2.2 on 2025-06-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="mari",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="father_from_mother",
                to="famille.person",
            ),
        ),
    ]
