# Generated by Django 4.2.23 on 2025-06-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="district",
                to="famille.district",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="nationalite",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Famille",
        ),
    ]
