# Generated by Django 4.2.23 on 2025-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0002_person_district_person_nationalite_delete_famille"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="est_vivant",
            field=models.CharField(
                blank=True,
                choices=[("V", "VIVANT"), ("D", "Décedé")],
                max_length=1,
                null=True,
            ),
        ),
    ]
