# Generated by Django 5.2.2 on 2025-06-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0003_continent_district_person_email_person_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="date_of_birth",
            new_name="date_decce",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="date_of_death",
            new_name="date_naissance",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="gender",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="mother",
            new_name="mere",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="first_name",
            new_name="nom",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="father",
            new_name="pere",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="last_name",
            new_name="prenom",
        ),
        migrations.AddField(
            model_name="person",
            name="famille",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnes",
                to="famille.famille",
            ),
        ),
    ]
