# Generated by Django 4.2.23 on 2025-06-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0004_alter_person_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="district",
                to="famille.district",
            ),
        ),
    ]
