# Generated by Django 5.2.2 on 2025-06-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0005_person_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="reseidence_actuel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residence",
                to="famille.pays",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="metier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personne",
                to="famille.metier",
            ),
        ),
    ]
