# Generated by Django 4.2.23 on 2025-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0006_metier_person_reseidence_actuel_person_metier"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="code_unique",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
