# Generated by Django 4.2.23 on 2025-06-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("famille", "0007_person_code_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="reseidence_actuel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residence",
                to="famille.ville",
            ),
        ),
    ]
